# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDCycleScrollViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDCycleScrollViewDemo

  target 'SDCycleScrollViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDCycleScrollViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDCycleScrollView', '~> 1.75'

end
